ai2cm/fv3gfs-fortran

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/model/fv_update_phys.F90
- FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
- FV3/atmos_cubed_sphere/tools/fv_io.F90
- FV3/atmos_cubed_sphere/tools/fv_nudge.F90
This PR:
- allows use of `fv_nwp_nudge` subroutine in `fv_nudge.f90` module
- allows output of nudging tendencies
- allows nudging of specific humidity
- allows nudging of temperature or pressure without also nudging winds.
One notable change is that I have removed the variable `q_dt` as an output of the `fv_nwp_nudge` subroutine, since the variable it was output to was not actually present in the routine that calls `fv_nwp_nudge` (`q_dt` is an optional argument to `fv_update_phys` that is not actually used).
Some of these changes were previously implemented in the old fv3gfs repo [here](https://github.com/VulcanClimateModeling/fv3gfs/commit/d2169e3a33965d0653259c6bd2e6c25c8bf72d46) and [here](https://github.com/VulcanClimateModeling/fv3gfs/commit/53cf031a06505208176262e63eb9498e73349273). …
> Enable use of fv_nwp_nudge subroutine

- .circleci/config.yml
- Makefile
- docker/Dockerfile
Added make directives `build_deps` and `push_deps` which create docker images with built FMS, ESMF, and serialbox codes, `pull_deps` which pulls them, and an environment argument `BUILD_FROM_INTERMEDIATE` which when set to `y` will cause build directives to set build args using these intermediate images instead of the intermediate build stages in the files that produce them. CircleCI is configured to use `pull_deps` and `BUILD_FROM_INTERMEDIATE`.
This allows us to build and then push intermediate images which then never need to get re-built on CircleCI. Previously these images were being periodically re-built when the build cache was being flushed.
This does require manual management of the remote images. No versioning has been implemented for these images.
> Enable docker pull for fms, esmf, and serialbox prebuilt images

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
- FV3/gfsphysics/GFS_layer/GFS_typedefs.F90
This option is needed in order to ensure that nudged runs are using the surface temperature from the GFS analysis.
> Add option to force physics SST to equal dynamical core surface temp

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_cubed_sphere/makefile
- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/model/fv_control.F90
- FV3/atmos_cubed_sphere/tools/coarse_grained_diagnostics.F90
- FV3/atmos_cubed_sphere/tools/coarse_graining.F90
- FV3/atmos_cubed_sphere/tools/online_coarse_graining.F90
This PR provides a slightly cleaned up sketch of how I've implemented online coarse-graining in SHiELD.  To keep the diff somewhat light, I've only added a single coarse diagnostic, `omega_coarse`, with the only strategy option being model-level coarse-graining.  It would be great to get some initial feedback on this work before I proceed any further.
So currently the way one would use this new functionality would be that they would need to activate coarse-graining in the namelist by providing a `coarsening_factor`, and setting the `do_coarse_graining` flag to `.true.`:
```
&fv_core_nml
...
do_coarse_graining = .true.
/
&online_coarse_graining_nml
coarsening_factor = 2
/
```
This is where the `strategy` would be specified, if multiple were implemented.  One can also set a separate I/O …
> Some initial infrastructure for online coarse-graining

- FV3/atmos_model.F90
This PR sets the total surface precipitation variable to zero during model initialization if `dycore_only=True`. Otherwise, since the physics routines are never called when using `dycore_only=True`, this variable remains equal to whatever value it has in the initial condition.
> Set surface precip to zero on init when using dycore_only=True

- FV3/makefile
Currently the coarse graining `depend` files are left over when running `make clean`. This adds `coarse_graining` to the `clean` directive in `FV3`.
> Add coarse graining to clean make directive

- tests/test_fv3_exe_restart.py
This PR updates the `test_fv3_exe_restart.py` script to use the regression test restart configuration, which uses remote data for the initial conditions instead of the old built-in restart data.
Note the test itself does pass and is not part of CI. This is mostly as part of updating documentation.
> use remote data for restart conditions

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/model/fv_update_phys.F90
- FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
- FV3/gfsphysics/GFS_layer/GFS_diagnostics.F90
- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
- FV3/gfsphysics/GFS_layer/GFS_typedefs.F90
- FV3/gfsphysics/physics/GFS_debug.F90
This PR adds a number of diagnostics to the fortran model, with the aim of making it possible to diagnose the tendencies of temperature and water vapor as contributed by each component of the physics.
**For verification purposes and convenience, it introduces two new dynamical core diagnostics:**
- `t_dt_phys`, which captures the total tendency of temperature in the dynamical core contributed by all physics routines.
- `qv_dt_phys`, which captures the total tendency of specific humidity in the dynamical core contributed by all physics routines.
*Note that both of these new dynamical core diagnostics do not include tendencies due to saturation adjustment performed within the dynamical core, or nudging to analysis.  This is consistent with how they are defined in SHiELD.*
**In addition, the …
> [VCMML-448] Add per-physics component temperature and water vapor tendency diagnostics

- FV3/gfsphysics/GFS_layer/GFS_diagnostics.F90
- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
While useful in SHiELD, where we run the model with a shorter timestep than the diagnostics interval, having the per-physics-component tendency diagnostics implemented in FV3GFS as time averages is actually inconvenient for us.  For instance, it would be convenient for us to record instantaneous physics tendencies, but save them out every two hours.  The current way the physics diagnostics are implemented in SHiELD and FV3GFS precludes this.  See an illustration of the existing problem in  [this notebook](https://github.com/VulcanClimateModeling/explore/blob/master/spencerc/2020-08-27-nudge-to-fine-test/2020-08-27-nudge-to-fine-test.ipynb).
These modified diagnostics are tested in a similar way to the original implementations [here](https://github.com/VulcanClimateModeling/explore/blob/mas …
> Convert per-physics-component tendency diagnostics from time average to instantaneous

- FV3/makefile
The current pkg-config install target only works if CCPP is not used in compilation. This PR adds a corresponding make target in the ifdef for when CCPP shows up in the compilation flags. The target itself is not tested, because we don't compile with CCPP.
> Added install target which works if ccpp is enabled

- FV3/conf/configure.fv3
This PR adds a default file (copied configure.fv3.gnu_docker) to use as `configure.fv3`, so that `make -C FV3` will work without source tree modifications.
> Copy configure.fv3.gnu_docker to use as default configure.fv3

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_model.F90
- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
- FV3/gfsphysics/GFS_layer/GFS_typedefs.F90
This PR fixes a bug introduced in #53. The way #53 was written we were adding the column moistening implied by nudging specific humidity from timestep `n` to the precipitation in timestep `n+1`.  This meant that in the first timestep, we were subtracting the uninitialized value of `column_moistening_implied_by_nudging` -- which could be anything -- from the precipitation felt in the physics.  In addition to being non-sensical, depending on what those uninitialized values were, this could lead to the model crashing.  
This PR fixes this by instead ensuring that we subtract the column moistening implied by nudging the specific humidity in timestep `n` to the precipitation in `n`.  Verification that this works can be found in the plots below.  
Here we can see that (1) the overall evolution …
> [VCMML-563] Ensure column moistening implied by nudging specific humidity is subtracted from the precipitation during the same timestep

- tests/serialized_test_data_generation/make_all_datasets.sh
This is a hotfix which gives better output in case the user specified a EXPERIMENT_PATTERN which does not match any configuration files in the `config` directory.
> [DSL-49] More verbose message if pattern doesn't match any experiments

- Makefile
- tests/pytest/README.md
- tests/pytest/set_reference.sh
Remove the Makefile target to update the references. Three reaasons:
- It was broken (the path specified was incorrect).
- It only updates the latest-serialize sums (is not general).
- It was not consistent with the documentation which said to use `set_reference.sh` directly.
Also minor update to documentation and `set_reference.sh`.
> Fix path in update_test_reference Makefile target

- tests/serialized_test_data_generation/Makefile
This might not work instantly, since only once the data is pushed to GCP the next time the `fortran_sha.txt` file will be removed.
> Exclude fortran_sha.txt from test data validation.

- example/submit_job.sh
These flags are no longer needed when using MPICH (as we do now).
> Update example/submit_job.sh for MPICH

- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
This is the alternative fix mentioned in #92.  This works without having to change the regression test checksums, which we might hope would be the case considering that the regression test only runs for 30 minutes and has a cycling frequency of 24 hours. In theory any change we make here shouldn't change answers, since the model isn't run long enough for cycling to be called.
Tests can be found in [this notebook](https://github.com/VulcanClimateModeling/explore/blob/master/spencerc/2020-10-15-debug-sst/2020-10-15-debug-sst.ipynb).  [EMC seems to think this fix is the correct approach.](https://github.com/NOAA-EMC/fv3atm/issues/79#issuecomment-710353844)
> Fix sea surface temperature cycling

- .circleci/config.yml
- Makefile
This commit pushes the dependencies images to GCR for every build and
tags by the commit sha. Previously this was only done manually
(presumably from someone's VM).
Resolves #89.
> Push dep images on every build

- requirements.txt
- tests/pytest/test_regression.py
After flipping the "requester-pays" switch on the public fv3config data the regression tests failed.  This is because the run mechanism through python does not pass the environment variable `GOOGLE_APPLICATION_CREDENTIALS` into the docker image.
Made adjustments to pass those along if the environment var is set.
> Add GOOGLE_APPLICATION_CREDENTIALS to the docker regression test run

- FV3/atmos_cubed_sphere/tools/coarse_grained_restart_files.F90
- FV3/coarse_graining/coarse_graining.F90
This is an implementation of our method of coarse-graining dynamical core restart files on surfaces of constant pressure.  A notebook verifying that this works against our offline Python method can be found [here](https://github.com/VulcanClimateModeling/explore/blob/master/spencerc/2020-11-18-verify-pressure-level-coarsening/2020-11-18-verify-pressure-level-coarsening.ipynb).
This builds off of work done in https://github.com/VulcanClimateModeling/fv3gfs-fortran/pull/58, which ported code to coarse-grain cell-center fields on surfaces of constant pressure.  Here we add the slightly more complicated procedure of doing this for the D-grid horizontal winds.  With each of those methods implemented, we can coarse-grain all the dynamical core restart variables on pressure.
> [VCMML-668] Add code to coarsen dynamical core restart files on constant pressure surfaces

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_cubed_sphere/model/dyn_core.F90
- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/model/fv_dynamics.F90
- FV3/atmos_cubed_sphere/model/fv_mapz.F90
- FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
This PR adds a new mass-conserving diagnostic for the pressure velocity, which is computed based on the outline [here](https://paper.dropbox.com/doc/Omega-calculation-in-FV3-ToalbcpBZXZq903Rf6aFV#:uid=561711331740789258903736&h2=Notes-on-FV3-code) (the original does not conserve mass in the non-hydrostatic version of the model).  Essentially this computes omega in non-hydrostatic mode the same way it is computed in hydrostatic mode.  We replace the original "omega" diagnostic with this new calculation and rename the old omega diagnostic "approximate_omega."
This diagnostic tends to behave more reasonably in the sense that it averages out more closely to zero in the global mean where the model uses pure pressure vertical levels.  See [this …
> [VCMML-679] Correct "omega" diagnostic to be mass-conserving in the non-hydrostatic model

- FMS/fms/fms.F90
- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/compile
- FV3/conf/configure.fv3.daint_gnu
- FV3/conf/configure.fv3.daint_intel
- FV3/conf/modules.fv3.daint_gnu
- FV3/conf/modules.fv3.daint_intel
- FV3/configure
This PR contains several changes to compile the model on Piz Daint using GNU / Intel compiler on bare-metal.
- Adaptions to the configure scripts for daint in `conf/configure.fv3.daint_<compiler>`
- Two bugfixes which were caught by the GNU compiler on Piz Daint (in `fms.F90` and `fv_arrays.F90`)
- Ressurection of the `compile` and `configure` scripts in the FV3 directory
> Changes in order to be able to compile bare-metal on Piz Daint

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/tools/coarse_grained_diagnostics.F90
- FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
This PR adds full and coarse resolution total tracer physics tendency diagnostics, i.e. for:
- `liq_wat` (`liq_wat_dt_phys`)
- `ice_wat` (`ice_wat_dt_phys`)
- `rainwat` (`qr_dt_phys`)
- `snowwat` (`qs_dt_phys`)
- `graupel` (`qg_dt_phys`)
[This notebook](https://github.com/VulcanClimateModeling/explore/blob/master/spencerc/2020-12-17-phys-dt/2020-12-17-phys-tend-diagnostics.ipynb) verifies that these diagnostics work, both in fine and coarse form, and in vertically integrated form.
> Add the rest of the total tracer physics tendency diagnostics

- FV3/atmos_model.F90
- FV3/coarse_graining/coarse_graining.F90
Fixes a bug in `atmos_model.F90` when diagnostics are called (`FV3GFS_diag_output()` on L918) but coarse-graining is not initialized and thus the dimensions (`is, ie, js, je`) of the argument `Atm(mytile)%delp(is:ie, js:je, :)` being passed in are not initialized.
The fix is to replace the call to get the dimensions to the `coarse_graining.F90` module with a call to `atmosphere_control_data` from `atmosphere.F90` which essentially does the same thing.
> Bug fix in coarse_graining.F90

- .dockerignore
- coverage.sh
- Introduce small bugfix in `coverage.sh`. Not sure how this ever worked before...
- Add `coverage_*` directories to `.dockerignore` in order to avoid rebuilds
Error on Mac OS was the following (so `Termination` is found by grep in stdout, but run still marked as unsuccessful):
```
+ gcovr -d -r /FV3/atmos_cubed_sphere --html --html-details -o index.html
[0] Termination                           0.620017      0.626813      0.622315      0.003178  0.010     0     0     5
Warning: Run does not seem to have been successfull. Check the rundir!
```
> Small bugfix in coverage.sh script to work again

- FMS/mpp/include/mpp_comm_mpi.inc
- FMS/mpp/include/mpp_comm_nocomm.inc
- FMS/mpp/include/mpp_comm_sma.inc
- FMS/mpp/include/mpp_util.inc
- FMS/mpp/mpp.F90
- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_cubed_sphere/model/fv_dynamics.F90
- FV3/atmos_model.F90
- FV3/coupler_main.F90
This PR introduces some modifications to the FMS timers present in the model (main API is `mpp_clock_id(), mpp_clock_begin(), mpp_clock_end()`). Since we want to make more detailed comparisons between the Fortran and Python version, it is important that these timings are easy to understand (no overlap, full coverage) and easy to process (parseable). This PR contains the following modifications:
- Avoid untimed sections (sub-sections should always add up to higher-level section)
- Split off timing of 1st trip through main loop (since it's polluted by initialization and memory allocations)
- Remove `atmosphere_state_update()` from FV3 Dycore timer and introduce separate timer to capture it.
- Introduce additional more fine-grain sections in FV3 (dyn_core, tracer, remap).
- Easier to parse …
> Cleanup and extend timers [DSL-313]

- .circleci/config.yml
We noticed the cloud sdk version changed over the weekend from 323.0.0 to 324.0.0.  It appears to be the reason why circle ci no longer has permissions to set the zone for the node it is running on. An alternative option to this PR is to give the Compute Viewer role to all of the fv3gfs-fort-gcp-ci service accounts, which would happen in a different repo or by hand. Here we pin the version of gcloud used by adding the gcp-cli orb and forcing the gcloud version to 323.0.0.
> pin the gcloud version for circleci

- FV3/atmos_cubed_sphere/model/dyn_core.F90
- tests/serialized_test_data_generation/Makefile
- tests/serialized_test_data_generation/configs/c12_54ranks_standard.yml
- tests/serialized_test_data_generation/configs/c12_6ranks_standard.yml
- tests/serialized_test_data_generation/configs/c48_6ranks_standard.yml
Reverts a recent change to the c12 and c48 standard namelists, since disabling `fill_dp` crashes these setups when run for a longer time period (e.g. 1 day).
> Revert `fill_dp=.false.` for c12 and c48 standard namelists

- FV3/gfsphysics/GFS_layer/GFS_typedefs.F90
The termination of the model now looks like the following if an "sgs_tke" tracer is not defined in the `field_table` of a simulation set to use the TKE-EDMF turbulence scheme.  Previously the model would uninformatively crash with a segmentation fault.
```
FATAL from PE     2: GFS_typedefs::control_initialize An sgs_tke tracer must be defined in the field_table if gfs_physics_nml.satmedmf is true.
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 9 RUNNING AT 25332af98bdf
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```
> Raise error for misconfigured field_tables

- FV3/atmos_model.F90
- FV3/io/FV3GFS_io.F90
This is now the output upon model termination if this occurs.  As in #132, the previous termination would be an uninformative segmentation fault.
```
FATAL from PE     0: FV3GFS_io::fv3gfs_diag_register Outputting 3D diagnostics from the physics requires gfs_physics_nml.ldiag3d be set to true.
FATAL from PE     1: FV3GFS_io::fv3gfs_diag_register Outputting 3D diagnostics from the physics requires gfs_physics_nml.ldiag3d be set to true.
FATAL from PE     0: FV3GFS_io::fv3gfs_diag_register Outputting 3D diagnostics from the physics requires gfs_physics_nml.ldiag3d be set to true.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
===================================================================================
=   BAD …
```
> Raise error for misconfigured 3D physics diagnostics

- .jenkins/actions/build_bare_metal.sh
- tests/serialized_test_data_generation/Makefile
- tests/serialized_test_data_generation/configs/c12_54ranks_standard.yml
- tests/serialized_test_data_generation/configs/c12_6ranks_standard.yml
- tests/serialized_test_data_generation/configs/c48_6ranks_standard.yml
This PR does three things:
1) Activates the GT4PY_DEV compile time flag in order to do an apples to apples comparison of what is being executed in Python and Fortran.
2) Switches off `fill_dp` again in the remaining namelists since it turns out that this seems to work on Piz Daint. Increase serialized data version number to 7.2.5 in order to have a clean slate and solve the "failing because of `input.nml` error".
3) Improves the Jenkins action to build bare metal executables on Piz Daint to be more parameterizable.
Since we don't have a PR builder for this on Jenkins, I've pointed the fv3gfs-fortran-build-bare-metal plan to this branch and given it a spin. Everything runs successfully: https://jenkins.ginko.ch/job/fv3gfs-fortran-build-bare-metal/56/
> Activate GT4PY_DEV for Daint executables and re-disable fill_dp

- .jenkins/actions/serialize_data.sh
- tests/serialized_test_data_generation/configs/c48_54ranks_baroclinic.yml
- tests/serialized_test_data_generation/configs/c48_54ranks_standard.yml
- tests/serialized_test_data_generation/make_all_datasets.sh
This PR removes data and run directories after each configuration in order to reduce disk space usage when generating regression data. It also does a cleanup of the Jenkins action script that is responsible for generating the regression data.
> Optimize space usage for regression data generation

- .jenkins/actions/benchmark_bare_metal.sh
This PR incorporates two bugifxes:
1) When running the benchmark on Piz Daint and tar'ing the latest run directory, the gzip option has been forgotten in the options to tar, even though the target files is named *.tar.gz.
2) The variable ${partition} was not defined.
> fix missing gzip option for tar

- benchmarking/daint_single_node/stdout_to_json.py
With the changes to the naming convention in https://github.com/VulcanClimateModeling/fv3core/pull/204 this PR adapts the format of the `.json` files we write out to keep them consistent
> changes to node-names in json

- benchmarking/daint_single_node/stdout_to_json.py
The hit count of aggregate timers should not be accumulated. This change removes the accumulation and ensures that all timers that are aggregated have the same hit count.
> Fix hit count of aggregate timers

- FV3/atmos_model.F90
- FV3/gfsphysics/GFS_layer/GFS_abstraction_layer.F90
- FV3/gfsphysics/GFS_layer/GFS_diagnostics.F90
- FV3/io/FV3GFS_io.F90
This PR refactors the diagnostics-manager-controlled diagnostics introduced in #112 such that they are defined within the same data structure as the other physics diagnostics.  It does so by simply adding a flag to the derived data type (default `.false.`) denoting whether a particular diagnostic is `diag_manager_controlled` or not.  The code path taken for sending data to the diagnostics manager then depends on the value of this flag.  It should not change any answers or functionality (regression tests confirm this).
xref: https://github.com/VulcanClimateModeling/fv3gfs-wrapper/issues/230
> Refactor diag_manager-controlled diagnostics for backwards compatibility

- FV3/atmos_cubed_sphere/driver/fvGFS/fv_nggps_diag.F90
The value of `nlevs` in `fv_nggps_diag.F90` is never initialized, which causes an error under some circumstances.
> Fix uninitialized value

- FV3/gfsphysics/GFS_layer/GFS_radiation_driver.F90
This fix avoids the use of undefined values in the radiation driver and as a consequence enables debug mode for the Intel compiler.
This fix does not affect results and only affects performance in a negligible way.
> Fix to avoid undefined values in radiation driver

- benchmarking/daint_single_node/stdout_to_json.py
Since the Intel compiler reports timers in a different order, the `4-Termination` is not the last timer being reported. This fixes the script in order to grab all of the timers.
> Fix script to extract timers

- tests/pytest/config/baroclinic.yml
Empty string causes a FileNotFoundError when using a pypi-installed version of fv3config.
The issue does not occur for local `pip install -e` installs. We don't know why, this should possibly be investigated.
> Convert empty string to empty list for no assets in baroclinic yaml

- FV3/conf/modules.fv3.daint_gnu
It does what it says.
This PR only affects bare-metal builds on Piz Daint.
> Hotfix to change GCC version back to 9.3.0 after Daint upgrade

- .jenkins/actions/build_bare_metal.sh
The tests of the bare metal executables have been running over since the upgrade. This is weird and will require further investigation. This PR should unblock the building of the executables so that the performance tests can be run on fresh executables in order to see what the actual change in performance for a more realistic setup actually is.
> Reduce runtime of test on Piz Daint

- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
- FV3/gfsphysics/GFS_layer/GFS_typedefs.F90
#93 restored the default behavior of the model SSTs, which was good, because it allowed the model SST to follow the climatology, but it broke our ability to set the sea surface temperature from the Python wrapper.  This PR adds a namelist flag that allows us to toggle between the two behaviors.
> Add namelist flag to restore ability to prescribe SST from Python wrapper

- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
This PR adds vertically integrated diagnostics for the tracers used in FV3GFS.  A notebook verifying that these work can be found [here](https://github.com/VulcanClimateModeling/explore/blob/master/spencerc/2021-04-23-vertically-integrated-diagnostics/2021-04-26-vertically-integrated-tracer-diagnostics.ipynb).
Resolves #182
> Add vertically integrated tracer diagnostics

- .circleci/config.yml
The Mac build were failing with this error:
```
Fatal error in MPI_Init: Invalid group, error stack:
MPIR_Init_thread(586)..............: 
MPID_Init(224).....................: channel initialization failed
MPIDI_CH3_Init(105)................: 
MPID_nem_init(324).................: 
MPID_nem_tcp_init(175).............: 
MPID_nem_tcp_get_business_card(401): 
MPID_nem_tcp_init(373).............: gethostbyname failed, static.38.39.189.154.cyberlynk.net (errno 0)
```
MPI on macs require some special DNS settings, see the stackoverflow link in the comment for more info.
> fix dns setting for mac builds

- nix/fv3/default.nix
This means that unstaged changes will not incur any rebuilds, and files
that aren't in version control (e.g. build artifacts) will not cause nix
to rebuild.
If you do want something to be included in a rebuild, it will need to be
staged to the git index (e.g. using git add).
> nix: use git for FV3 source

- benchmarking/daint_single_node/stdout_to_json.py
Update to https://github.com/VulcanClimateModeling/fv3gfs-fortran/pull/196 to only report times per timestep instead of total time.
> Report times per timestep instad of total time

- docker/Dockerfile
Update Dockerfile to use a different boost download since previous link is no longer valid
> update boost download location

- coverage.sh
This PR fixes the coverage.sh script to work again and adapts it so it reports coverage information of all /FV3 instead of seperately only reporting the physics and dynamics coverage.
> Fix coverage.sh and report coverage of all /FV3

- tests/serialized_test_data_generation/configs/c320_6ranks_baroclinic.yml
Since a more recent version, fv3config now supports passing emply list's for orography, which is not required for running a baroclinic testcase.
> Remove dependency on orography files for baroclinic configurations

- benchmarking/daint_single_node/stdout_to_json.py
The `stdout_to_json.py` had an error (missing function argument) which lead to failures. This PR fixes this.
> Fix Jenkins benchmarks

- tests/serialized_test_data_generation/Makefile
Currently the makefile and jenkins plans have manual logic for setting up test directories, where an experiment yml file must be moved to input.yml before the directory can be used. This tightly couples the EXPERIMENT argument, the data path, and the remote data file structure. 
Here we  rename the yml files in the data directories to input.yml so the remote data is useful as-is.
> also generate an input.yml file

- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/tools/fv_grid_tools.F90
The `init_grid` subroutine has conditionals to determine whether a tile corner is present, and then does specific calculations for the c-grid area at those corners. Currently those conditionals are never set, but are consumed. To ensure consistency (and to bring the code in-line with the NOAA code) these should be set to `.false.` at the start of `fv_arrays`.
Code Changes:
- `fv_arrays.F90`: set sw_corner se_corner, ne_corner, and nw_corner to false in the grid type allocations
> corner conditionals should be initialized before they're consumed

- FV3/gfsphysics/GFS_layer/GFS_diagnostics.F90
- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
- FV3/gfsphysics/GFS_layer/GFS_typedefs.F90
- tests/emulation/README.md
- tests/pytest/config/emulation.yml
Add 6 new diagnostics quantities. This is more robust to do in fortran because it already handles multiple blocks and the conversion from `(i,level)` to `(x,y,level)`.
- `tendency_of_air_temperature_due_to_zhao_carr_emulator`
- `tendency_of_cloud_water_due_to_zhao_carr_emulator`
- `tendency_of_air_specific_humidity_due_to_zhao_carr_emulator`
- `tendency_of_air_temperature_due_to_zhao_carr_physics`
- `tendency_of_cloud_water_due_to_zhao_carr_physics`
- `tendency_of_air_specific_humidity_due_to_zhao_carr_physics`
> Add emulator diagnostics

- FV3/atmos_model.F90
- FV3/gfsphysics/GFS_layer/GFS_driver.F90
- FV3/gfsphysics/GFS_layer/GFS_typedefs.F90
The zhao carr scheme requires past temperature and humidity data to be restarted. This data is stored correctly in the restarts, but the model overwrites it on the first timestep before the microphysics are called. This leads to 5x too negative values of the Zhao-carr humidity tendency in the initial timestep.
Resolves #240
I verified this works with this script:
<details>
```
set -e 
cat << EOF > fv3config.yml
data_table: default
diag_table:
base_time: 2000-01-01 00:00:00
file_configs:
- field_configs:
- field_name: tendency_of_air_temperature_due_to_emulator
module_name: zhao_carr_microphysics
output_name: tendency_of_air_temperature_due_to_zhao_carr_emulator
packing: 2
reduction_method: none
regional_section: none
time_sampling: all
- field_name: tendency_of_cloud_water_due_to_emulator …
```
> Fix zhao-carr restart bug

- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
- nix/fv3/default.nix
- tests/emulation/README.md
- tests/emulation/emulation/emulate.py
The temperature and humidity states after gscond are used to compute a relative
humidity tendency in the following timestep. Also, we always run the model with
the same physics (dtp) and dynamics (dtf) timestep, so the tp1 and cp1 variables
are identical to cp. dtp is actually set equal to dtf in the model startup.
See this
[notebook](https://github.com/ai2cm/explore/blob/master/noahb/emulation/microphysics/2021-11-03-verify%20tbd%20data.ipynb)
for proof.
* Remove the redundnant call py fort state setting for tp1_cpf, etc
* Rename the output of `tp` etc to be more accurate
* Save the temperature and humidity state after `gscond`
* Install black in nix environment to make development easier
> emulation: save state after gscond

- .jenkins/actions/serialize_data.sh
Set CALLPYFORT to empty in the jenkins action so that it's not on for serialization.
> CALLPYFORT is off for serialization

- .gitignore
- Makefile
- README.md
- nix/fv3/configure.fv3
- nix/fv3/default.nix
./coverage.sh only works with docker. Its logic is tightly interwoven with environment management with docker/pip. I implemented some makefile targets which assume all the relevant tools and dependencies are installed and therefore should work from within nix, docker container, or on bare metal.
> implement code coverage reports for native builds

- .circleci/config.yml
- nix/fv3/default.nix
- requirements.txt
- tests/pytest/config/restart.yml
- tests/pytest/test_regression.py
This PR adds a test to ensure that segmented runs produce identical results to continuous runs for a series of configurations.  
For this test to pass, a change to fv3config was required (see more discussion in ai2cm/fv3config#147 and ai2cm/fv3config#144), which has been included in its latest release, v0.9.0.  Accordingly this PR bumps the versions of some dependencies in our testing environments:
- In the nix environment, fv3config is updated from version 0.7.1 to 0.9.0.
- In the default test environment, fv3config is updated to version 0.9.0 and fsspec and gcsfs are updated to their latest versions, 2022.3.0 and 2022.3.0.  Upgrading gcsfs to version 2022.3.0 also required updating the Python version to at least 3.7.0.  Without updating fsspec and gcsfs, the tests would fail to download …
> Add restart reproducibility regression test

- .jenkins/actions/build_bare_metal.sh
With the additional install of `gcsfs`, python version needs to be >3.7. Updating daint to use python 3.8.5.
> Update python version used on daint for CI

- docker/Dockerfile
- tests/serialized_test_data_generation/Makefile
UPDATE -- the fix is no longer needed, but we need a new data version number, the current one does not match 8.0.3
_A quick fix for a new error:
GPG error: https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80
recommended here: 
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772
and here
https://github.com/NVIDIA/nvidia-docker/issues/1631_
> data version 8.0.4

- FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90
- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/model/fv_dynamics.F90
- FV3/atmos_cubed_sphere/model/fv_mapz.F90
- FV3/atmos_cubed_sphere/model/fv_update_phys.F90
- FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
- README.md
This PR adds 2D and 3D temperature and specific humidity tendency diagnostics from the dycore fast saturation adjustment. FV3GFS didn't previously output these tendencies, which made computing complete "physics" tendencies difficult in the context of diagnostic budgets. 
See notebook [here](https://github.com/ai2cm/explore/blob/master/brianh/2022-05-06-N2F-40-day-Q-comparison/2022-05-16-debug-fast-sat-adj-diags.ipynb) that plots the mean 2D and 3D diagnostics output from a 10-day nudged run. For reference, the column moistening tendencies look like about the same (but sign flipped) pattern as what we [inferred (see Figure 8 bottom panel)](https://docs.google.com/document/d/1-bHzB75TD7nhhWF4TnZAoKhweCgKEgXDkZ12TV2Cw4g/edit#heading=h.1dkyg7nqpvqg) to be missing fast saturation adjustment …
> FV3: fv_sat_adj tendency diags

- docker/Dockerfile
- tests/serialized_test_data_generation/Makefile
- tests/serialized_test_data_generation/serialbox_to_netcdf.py
This PR adds compression of greater than 2D variables to serialbox_to_netcdf.py, reducing output file sizes by about 40%. It also installs the python dependencies required within the docker image, reducing the time needed when converting data.
> Add compression to converted netcdf data, install deps in docker

- tests/serialized_test_data_generation/Makefile
We bump the version to 8.1.0 now that the serialized data also include netcdf format.
> Generate 8.1.0 data with netcdf files

- .circleci/config.yml
- FV3/atmos_model.F90
- tests/pytest/test_regression.py
Originally, by default, if `fdiag` was provided as a scalar value and `fhouthf`  was less than zero, the physics diagnostics would be output on regular intervals of length `fhout` hours for a finite number of total simulated hours, governed by `fhmax`.  This can be problematic in long simulations.  Simply using a large default value of `fhmax` is not tenable, because we cannot allocate an infinitely large `fdiag` array (which is what the original physics diagnostics approach uses under the hood).  
This PR changes the default behavior such that physics diagnostics will now be output indefinitely on a regular interval of `fhout` hours, ignoring any values set for the `fdiag`, `fhmax`, `fhmaxhf`, or `fhouthf` parameters.
While in practice we do not use the ability of `fdiag` to output …
> Set the model to output physics diagnostics indefinitely by default

- FV3/wrapper/fv3gfs/wrapper/physics_properties.json
- FV3/wrapper/templates/_wrapper.pyx
- FV3/wrapper/templates/physics_data.F90
The goal of this PR is to add a subroutine to physics_data.F90 to get orographic variables ( hprime in fortran) outputs. 
- get_n_orographic_variables is added to physics_data.F90 
- get_quantity_factory() was modified in the  _wrapper.pyx to output a hard-coded orographic variables 
- the physics_properties.json  file was modify to output this new variable. 
The 11 tests with CI located in FV3/wrapper/tests/pytest pass successfully.
> wrapper: add getter/setter for orographic variables 

- tests/serialized_test_data_generation/Makefile
- tests/serialized_test_data_generation/serialbox_to_netcdf.py
In `FVDynamics-Out`, the tracers have filled values, causing a validation error. In this PR, we subset them so that only the compute domain is written out.
> Subset fvdynamics-out tracers

- FV3/conf/configure.fv3.gnu_docker
- FV3/conf/configure.fv3.gnu_docker_serialize
- FV3/conf/configure.fv3.nix
- docker/Dockerfile
For other platforms `NCEPLIBS_DIR` refers to the base NCEPlibs install directory rather than `NCEPlibs/lib`.  In addition, for ESMF-related environment variables it [is recommended](https://earthsystemmodeling.org/docs/release/ESMF_5_2_0p1/ESMF_usrdoc/node9.html#SECTION00098000000000000000) to include the `ESMFMKFILE` and build up from the variables defined in there.
Making sure these variables have a consistent meaning across configure files will make it easier write general scripts to build the model on multiple platforms.
(This is split out of #325 to make for a more atomic change)
> Harmonize definition of NCEPlibs and ESMF environment variables in configure files

- FV3/conf/configure.fv3.gaea
- FV3/conf/configure.fv3.gnu_docker
This PR addresses #330 by enabling us to override the compilers defined in existing configure files using environment variables.
> Enable overriding compiler settings with environment variables

- FV3/wrapper/lib/coupler_lib.F90
- FV3/wrapper/templates/_wrapper.pyx
- FV3/wrapper/tests/from_restarts_config.yml
- FV3/wrapper/tests/test_all_mpi_requiring.py
- FV3/wrapper/tests/test_get_initialization_time.py
- FV3/wrapper/tests/util.py
Adds a getter for the model "initialization time" to the Fortran wrapper. Note that initialization time has a special meaning to the GFS physics, which is the beginning time of an initial run (of potentially multiple segments via restarting), i.e., not necessarily the time at which the wrapper is initialized. This information is necessary for porting some aspects of the GFS physics (see #https://github.com/ai2cm/fv3config/issues/147 for some examples).
> Wrapper: Model initialization time getter

- .circleci/config.yml
- .pre-commit-config.yaml
- FV3/wrapper/Makefile
- FV3/wrapper/tests/pytest/test_regression.py
- Makefile
- pytest.ini
- tests/pytest/test_regression.py
The nix tests in this repo have gotten fairly time consuming.  For example [a recent workflow](https://app.circleci.com/pipelines/github/ai2cm/fv3gfs-fortran/2425/workflows/4be01fd5-caae-4229-97f9-34a2886f5875/jobs/4274) took an hour and five minutes.  This is more than double the typical amount of time required for the docker tests (see a comparable workflow [here](https://app.circleci.com/pipelines/github/ai2cm/fv3gfs-fortran/2423/workflows/c2667ebd-69d8-427a-94a6-49beb271bd48/jobs/4269)).  This PR breaks the nix tests up into a few categories:
- basic: these are tests that will be run upon every push to every PR.  These represent something of a bare minimum requirement: the model and wrapper build successfully, answers don't change for our default regression test, and the model …
> Defer slow (not necessarily essential) tests to after merge

- FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
- FV3/wrapper/tests/pytest/_regtest_outputs/test_regression.test_fv3_wrapper_regression[emulation.yml].out
I found three inconsistencies in our Zhao-Carr code that were messing up the diagnostics.  Each one is addressed in a commit if it's easier to review that way.  
1.  The offline fortran output to the diagnostics had an improper adjustment where the gscond emulated state was removed before adding back the total ZC update.  The offline case doesn't have the emulation updated state, so it shouldn't apply.
2. The online fortran diagnostics for precpd were based off the scheme run with the emulated gscond outputs as inputs.  For our emulation setup, we don't currently base the precpd prediction off the emulated gscond outputs so the piggy-backed comparison is not consistent.
3. The precipitation output was being applied from the emulator in the offline case
To remedy this, I made a few updates …
> Fix Zhao-Carr emulation piggy-back diagnostics

- FV3/atmos_cubed_sphere/tools/external_ic.F90
- FV3/wrapper/fv3gfs/wrapper/__init__.py
- FV3/wrapper/fv3gfs/wrapper/physics_properties.json
- FV3/wrapper/templates/_wrapper.pyx
- FV3/wrapper/templates/dynamics_data.F90
- FV3/wrapper/tests/test_all_mpi_requiring.py
- FV3/wrapper/tests/test_wind_transformations.py
This PR adds Python-wrapped versions of the wind transformation subroutines contained in the dynamical core.  This will allow us to more easily convert the horizontal winds between the D-grid and A-grid from within a Python-wrapper runfile.  
The primary motivation here is to enable us to more flexibly translate wind tendency updates made on the A-grid to the D-grid (e.g. to enable nudging toward A-grid winds or applying ML-predicted tendency corrections without modifying fields in the physics output state).  For this we technically only need the A to D grid transformation, but the D to A grid transformation could potentially have use-cases as well (e.g. if we ever wanted to directly output A-grid wind nudging tendencies when we were nudging to D-grid winds).
The `cubed_to_latlon` and …
> Add Python-wrapped versions of the wind transformation subroutines

- FV3/conf/configure.fv3.gaea-c5
- FV3/conf/modules.fv3.gaea-c5
This PR adds configuration information for building the fortran model on Gaea's new C5 partition.  This is effectively a new system and requires different modules than the previous C3/C4 partitions (which the existing `gaea` configuration is targeted to).  ORNL will eventually recommend everyone move their work to the C5 partition and they are encouraging users to try running their jobs there now.
For reviewing purposes, this is a diff of the `configure.fv3.gaea` file with the new `configure.fv3.gaea-c5` file:
```diff
$ diff configure.fv3.gaea configure.fv3.gaea-c5
52c52,59
< FPPFLAGS := -fpp -Wp,-w $(INCLUDE) -fPIC
---
> # The FPPFLAGS option -DHARMONIZE_PROCEDURE_POINTER_INTENTS is specified
> # to avoid unwanted errors when compiling the model. The source of the
> # errors is the …
```
> Add `gaea-c5` platform for building on Gaea's C5 partition

- FV3/atmos_cubed_sphere/model/fv_arrays.F90
- FV3/atmos_cubed_sphere/model/fv_dynamics.F90
- FV3/atmos_cubed_sphere/model/fv_update_phys.F90
- FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
This PR adds column-integrated physics tendency diagnostics for temperature and specific humidity.  In the case of temperature we follow what was done for the column integrated nudging and fv_sat_adj tendencies, where we scale the column integrated result by either Cp or Cv depending on whether the model is run hydrostatically or non-hydrostatically.  As in those cases we do not take into account moist effects when computing these values.  That's something we could eventually think about modifying, but might be better for a future PR.
Note: I moved the `compute_column_integral` subroutine to the `fv_diagnostics` module to work around a circular import.
[This notebook](https://github.com/ai2cm/explore/blob/master/spencerc/2023-04-07-column-physics-diagnostics/2023-04-07-test-column-physics- …
> Add column integrated physics tendency diagnostics

- FV3/conf/modules.fv3.gaea-c5
This PR updates the modules loaded for building FV3GFS on Gaea's C5 partition.  We update `intel-classic/2022.0.2` to `intel-classic/2022.2.1` to be consistent with its current default version on C5, and perhaps more importantly, update `cray-mpich/8.1.16` to `cray-mpich/8.1.25`, since `cray-mpich/8.1.16` was removed in a recent software update.
> Update modules for `gaea-c5` platform

- FV3/gfsphysics/GFS_layer/GFS_diagnostics.F90
The existing `tsfc`, `u10m`, and `v10m` fields are hard-coded to be instantaneous diagnostics.  It is currently not possible to output interval average versions of these fields.  This PR addresses this issue by adding diagnostics-manager-controlled versions of these fields  Implementing them as diagnostics-manager-controlled allows for flexibility in saving them out as instantaneous fields or interval averages with flexible averaging windows, just like diagnostics in the dynamical core.  
The added fields are suffixed with `_via_diagnostics_manager`.  This name is a little verbose, but I'm hesitant to remove the existing non-diagnostics-manager versions of these fields for backwards compatibility.  Fortunately this suffix can be removed by specifying a custom output name in the …
> Add diagnostics-manager-controlled versions of `tsfc`, `u10m`, and `v10m`

- FV3/gfsphysics/GFS_layer/GFS_diagnostics.F90
This PR adds `coarse_graining_method` attributes to the `TCDC_aveclm`, `TCDC_avehcl`, `TCDC_avemcl`, `TCDC_avelcl`, and `sw_dnfxc` physics diagnostics, making them possible to coarse grain online.  `sw_dnfxc` is the instantaneous downward shortwave radiative flux; it is not possible to use when compiling with `gfortran`, e.g. in our Docker images, but is possible to use with Intel compilers, e.g. on Gaea.
[This notebook](https://github.com/ai2cm/explore/blob/master/spencerc/2023-08-11-implement-new-coarse-diagnostics/2023-08-11-validate-new-diagnostics.ipynb) does a sanity check on the coarse cloud cover fields, verifying that their offline coarsened values match their online coarsened values.
> Make cloud cover and instantaneous downward shortwave diagnostics coarsenable

- FV3/coarse_graining/coarse_graining.F90
This is a typo that made it into #370.  Somehow when coarsening at C12 resolution by only a factor of two it did not make a difference in the result, but when validating blended-area-weighted coarse-graining in SHiELD, going from C48 resolution to C6, it emerged.  
Fortunately we have not used the blended coarse-grained D-grid winds for any experiments up to this point--we have switched to nudging to A-grid winds in nudged runs--so this has not affected any important results.
[This notebook](https://github.com/ai2cm/explore/blob/master/spencerc/2023-08-18-validate-blended-area-weighted-coarsening-SHiELD-bug.ipynb) illustrates the symptom of the bug (large differences between online and offline coarsened values for the D-grid x-wind in the uppermost row of each tile); [this …
> Fix bug in computing the blending pressure for the D-grid x-wind

- FV3/io/FV3GFS_io.F90
This small PR provides a small optimization to the pressure-level-extrapolate coarse-graining code pathway in the physics diagnostics following #370.  #370 introduced the need to compute blending weights when using blended-area-weighted coarse-graining.  We do not need to do this for the pressure-level and pressure-level-extrapolate modes, but accidentally left the blending weights to be computed in the pressure-level-extrapolate case within the physics diagnostics.  This PR fixes that.  It should not change answers, but should make things slightly more efficient.
> Optimize pressure-level-extrapolate coarsening for physics diagnostics

- .circleci/config.yml
- tests/pytest/test_regression.py
This PR fixes errors in test skipping logic introduced in #379 (see [this CI run](https://app.circleci.com/pipelines/github/ai2cm/fv3gfs-fortran/2682/workflows/e71d0119-0c60-44c7-bf4f-d97f10ccbb0b/jobs/5541)).  In that PR these particular tests were configured only to be attempted to be run upon merges to master, because they would be skipped anyway.  
This PR also now ensures that we at least attempt to run the emulation tests in debug mode in CI when the developer requests to, since it will exercise the skipping logic before merging to master (upon which all pure fortran tests are attempted to be run in both repro and debug mode).
[This CI job](https://app.circleci.com/pipelines/github/ai2cm/fv3gfs-fortran/2688/workflows/0c3ca3a2-3b4d-46d6-8cca-a65e1b9a5a0f/jobs/5557) confirms that this …
> Fix test skipping logic in debug-mode emulation tests
