ai2cm/fv3gfs-fortran

tests/test_fv3_exe_restart.py
Fixes an issue where the config file might not be purposed for the new fv3atm sources.
=> Use local config file instead of get_default_config for restart tests

FV3/atmos_cubed_sphere/model/fv_arrays.F90, FV3/atmos_cubed_sphere/model/fv_update_phys.F90, FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
It's useful to have a column-integrated diagnostic for the nudging moistening.
=> Add diagnostic for column-integrated moistening from nudging

README.md
I thought it would be nice to document this somewhere.
=> Describe repository structure in the README

.jenkins/actions/serialize_data.sh, tests/serialized_test_data_generation/Makefile, tests/serialized_test_data_generation/configs/c12_54ranks_standard.yml, tests/serialized_test_data_generation/configs/c12_6ranks_baroclinic.yml, tests/serialized_test_data_generation/configs/c12_6ranks_standard.yml, tests/serialized_test_data_generation/configs/c48_6ranks_baroclinic.yml, tests/serialized_test_data_generation/configs/c48_6ranks_standard.yml, tests/serialized_test_data_generation/configs/c96_54ranks_baroclinic.yml, tests/serialized_test_data_generation/configs/c96_6ranks_baroclinic.yml, tests/serialized_test_data_generation/make_all_datasets.sh
=> Add namelists for c96 baroclinic setup for benchmarking [DSL-315]

FV3/coupler_main.F90
Sorry for breaking master with the PR regarding timers. Seems like a bug only appeared when doing more than 1 timestep. The issue was the `if (nc > 1)` which ended up callling `mpp_clock_end(mainLoop1st)` multiple times, even though the timer has already been stopped.
=> Hotfix of bug in timers

benchmarking/daint_single_node/stdout_to_json.py
follow up to https://github.com/VulcanClimateModeling/fv3gfs-fortran/pull/149
=> Fix error in stdout_to_json.py because of naming change.

.jenkins/actions/build_bare_metal.sh, FV3/atmos_cubed_sphere/tools/fv_diagnostics.F90
Removes dependency on vcm_1.0 virtual environment stored in /project/s1053 and simply installs venv on the fly using `requirements.txt` file.
=> Fix: Remove dependency on vcm virtual environment

.jenkins/actions/benchmark_bare_metal.sh, benchmarking/daint_single_node/stdout_to_json.py
Updates the timing format to match https://github.com/VulcanClimateModeling/fv3core/pull/489
=> Update performance generation for new format

.circleci/config.yml, default.nix, nix/nceplibs/default.nix
nixpkgs nearly has a new release with many package fixes and updates
=> Update base nixpkgs to release-21.05

tests/serialized_test_data_generation/configs/c160_6ranks_baroclinic.yml, tests/serialized_test_data_generation/configs/c320_6ranks_baroclinic.yml, tests/serialized_test_data_generation/configs/c384_6ranks_baroclinic.yml, tests/serialized_test_data_generation/configs/c64_6ranks_baroclinic.yml, tests/serialized_test_data_generation/configs/c80_6ranks_baroclinic.yml
Note: These are copies of c192_6ranks_baroclinic.yml where only the name of the configuration as well as npx/npy have been modified in the *.yml file.
=> Add new configurations for benchmarking

FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
=> Fix typo in emulation name

FV3/conf/configure.fv3.daint_gnu, FV3/conf/modules.fv3.daint_intel
Update the config files for daint gnu and intel compilation.
=> Update daint configuration

.jenkins/actions/benchmark_bare_metal.sh, .jenkins/actions/build_bare_metal.sh, .jenkins/actions/serialize_data.sh
Add requester bucket environment variable explicitly due to the change in fv3config.
=> Jenkins CI update

tests/serialized_test_data_generation/Makefile
Update data version since run answers changed slightly.
=> serialized data version 8.0.3

FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90, nix/fv3/default.nix
Fixes a diagnostic bug in the emulation code (https://github.com/ai2cm/fv3net/issues/1838).
See commit messages for more motivation.
=> Fix zhao carr diags

tests/serialized_test_data_generation/Makefile, tests/serialized_test_data_generation/serialbox_to_netcdf.py
Currently uploaded savepoint data exists only in serialbox form. This PR converts that data to netCDF as well before the data is uploaded.
=> Convert savepoints to netcdf before uploading

.circleci/config.yml, tests/serialized_test_data_generation/Makefile
Update `SUBSET_PHYSICS` to `AI2_SUBSET_PHYSICS` and bump data version to 8.0.5.
=> Update serialized data to 8.0.5

tests/serialized_test_data_generation/Makefile
=> Remove incorrect -it flag in serialized data conversion

FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90, FV3/atmos_model.F90, FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90, FV3/gfsphysics/GFS_layer/GFS_typedefs.F90, FV3/io/FV3GFS_io.F90, tests/pytest/conftest.py, tests/pytest/prescribed_ssts.py, tests/pytest/test_regression.py
This PR ports the code to prescribe a time-varying SST (and optionally sea ice) pattern from a file from the public [SHiELD_physics repository](https://github.com/NOAA-GFDL/SHiELD_physics).  It also adds a regression test.  The regression test is fairly involved, but doubles as documentation for how to use this feature of the model which has a few gotchas that are described in the testing code.
=> Port SST prescribing code from SHiELD

Makefile, README.md, nix/fv3/default.nix
Addresses some issues making it more challenging to use the nix dev environment: #296, #314
=> nix: dev workflow items

benchmarking/daint_multi_node/scratch
Fixes https://github.com/ai2cm/fv3gfs-fortran/issues/320 where this breaks our builds of fv3net.
=> Delete scratch symlink

FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90, tests/pytest/_regtest_outputs/test_regression.test_checksum_emulation[Linux].out, tests/pytest/test_regression.py
Resolves #343 
Note: I noticed I had not synced another commit which removed unused code for #342.  Included that here.
=> Update missing emulation mark test

tests/serialized_test_data_generation/README.md
This PR adds some additional wordings for people generating translate dataset without write access to AI2 google bucket.
=> Add doc for generating translate dataset

FV3/gfsphysics/GFS_layer/GFS_physics_driver.F90
In #304 we prescribed the sea ice just before we prescribed the surface temperature, but this is not quite [how things were done in SHiELD](https://github.com/NOAA-GFDL/SHiELD_physics/blob/b285c9d05bda69ea7ee877b46edcd5ce28d31b92/GFS_layer/GFS_physics_driver.F90#L727-L744).  This PR puts the sea ice prescription code just before `islmsk` is initialized in the physics driver, which may be necessary to avoid instability.
=> Prescribe sea ice at a similar point in the physics driver as SHiELD
